In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
data=pd.read_csv("news.csv")

In [3]:
data.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [6]:
res=data.label

In [47]:
newd=data.title+data.text
newd

0       You Can Smell Hillary’s FearDaniel Greenfield,...
1       Watch The Exact Moment Paul Ryan Committed Pol...
2       Kerry to go to Paris in gesture of sympathyU.S...
3       Bernie supporters on Twitter erupt in anger ag...
4       The Battle of New York: Why This Primary Matte...
5       Tehran, USA  \nI’m not an immigrant, but my gr...
6       Girl Horrified At What She Watches Boyfriend D...
7       ‘Britain’s Schindler’ Dies at 106A Czech stock...
8       Fact check: Trump and Clinton at the 'commande...
9       Iran reportedly makes new push for uranium con...
10      With all three Clintons in Iowa, a glimpse at ...
11      Donald Trump’s Shockingly Weak Delegate Game S...
12      Strong Solar Storm, Tech Risks Today | S0 News...
13      10 Ways America Is Preparing for World War 3Oc...
14      Trump takes on Cruz, but lightlyKilling Obama ...
15      How women lead differentlyAs more women move i...
16      Shocking! Michele Obama & Hillary Caught Glamo...
17      Hillar

In [48]:
x_train,x_test,y_train,y_test=train_test_split(data["text"], res, test_size=0.2, random_state=7)

In [49]:
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)

In [50]:
k=tfidf_vectorizer.get_feature_names()

In [52]:
tfidf_test.shape

(1267, 61651)

In [53]:
from sklearn import tree

In [54]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(tfidf_train, y_train)

In [55]:
pred=clf.predict(tfidf_test)

In [56]:
score=accuracy_score(y_test,pred)

In [57]:
score

0.797947908445146

In [59]:
## passive classifier
pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)

y_pred=pac.predict(tfidf_test)
score=accuracy_score(y_test,y_pred)
score

0.9265982636148382

In [79]:
x_train,x_test,y_train,y_test=train_test_split(newd, res, test_size=0.2, random_state=7)

In [75]:
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)

In [68]:
tfidf_train.shape

(5068, 65348)

In [63]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(tfidf_train, y_train)

In [65]:
pred=clf.predict(tfidf_test)
score=accuracy_score(y_test,pred)
score

0.8011049723756906

In [66]:
## passive classifier
pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)

y_pred=pac.predict(tfidf_test)
score=accuracy_score(y_test,y_pred)
score

0.9210734017363852

In [ ]:
#neural classifier

In [130]:
x_train,x_test,y_train,y_test=train_test_split(newd, res, test_size=0.2, random_state=7)

In [131]:
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)

In [132]:
tfidf_train.shape

(5068, 65348)

In [133]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y_train=lb.fit_transform(y_train)
y_test=lb.fit_transform(y_test)
y_test

array([1, 0, 1, ..., 1, 0, 1])

In [134]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [135]:
model = Sequential()
model.add(Dense(132, input_dim=65348, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(8, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(4, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(1, activation='sigmoid'))

In [136]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [137]:
model.fit(tfidf_train, y_train, epochs=15, batch_size=10)

Epoch 1/15
5068/5068 [==============================] - 13s 3ms/step - loss: 0.4624 - acc: 0.7459
Epoch 2/15
5068/5068 [==============================] - 12s 2ms/step - loss: 0.2416 - acc: 0.9084
Epoch 3/15
5068/5068 [==============================] - 12s 2ms/step - loss: 0.1640 - acc: 0.9501
Epoch 4/15
5068/5068 [==============================] - 12s 2ms/step - loss: 0.1248 - acc: 0.9599
Epoch 5/15
5068/5068 [==============================] - 13s 2ms/step - loss: 0.0996 - acc: 0.9639
Epoch 6/15
5068/5068 [==============================] - 12s 2ms/step - loss: 0.0918 - acc: 0.9692
Epoch 7/15
5068/5068 [==============================] - 12s 2ms/step - loss: 0.0936 - acc: 0.9732
Epoch 8/15
5068/5068 [==============================] - 13s 3ms/step - loss: 0.0624 - acc: 0.9844
Epoch 9/15
5068/5068 [==============================] - 12s 2ms/step - loss: 0.0645 - acc: 0.9846
Epoch 10/15
5068/5068 [==============================] - 13s 2ms/step - loss: 0.0536 - acc: 0.9872
Epoch 11/15
5068/50

In [138]:
predict=model.predict_classes(tfidf_test)
predict

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [140]:
score=accuracy_score(y_test,predict)
score

0.920284135753749

In [142]:
#neural alone with title
x_train,x_test,y_train,y_test=train_test_split(data["text"], res, test_size=0.2, random_state=7)
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)
tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)
tfidf_train.shape

(5068, 61651)

In [143]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y_train=lb.fit_transform(y_train)
y_test=lb.fit_transform(y_test)
y_test

array([1, 0, 1, ..., 1, 0, 1])

In [144]:
model = Sequential()
model.add(Dense(132, input_dim=61651, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(8, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(4, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(1, activation='sigmoid'))

In [145]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [146]:
model.fit(tfidf_train, y_train, epochs=15, batch_size=30)

Epoch 1/15
5068/5068 [==============================] - 7s 1ms/step - loss: 0.5939 - acc: 0.6529
Epoch 2/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.3404 - acc: 0.8279
Epoch 3/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.2235 - acc: 0.8917
Epoch 4/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.1476 - acc: 0.9453
Epoch 5/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.1236 - acc: 0.9548
Epoch 6/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.1161 - acc: 0.9596
Epoch 7/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.1105 - acc: 0.9572
Epoch 8/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.1132 - acc: 0.9572
Epoch 9/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.1068 - acc: 0.9572
Epoch 10/15
5068/5068 [==============================] - 5s 1ms/step - loss: 0.1046 - acc: 0.9597
Epoch 11/15
5068/5068 [======

In [148]:
predict=model.predict_classes(tfidf_test)
predict

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [149]:
score=accuracy_score(y_test,predict)
score

0.9281767955801105

In [150]:
##trying another model
model.fit(tfidf_train, y_train, epochs=15, batch_size=5)

Epoch 1/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0997 - acc: 0.9615
Epoch 2/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0987 - acc: 0.9588
Epoch 3/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.1002 - acc: 0.9594
Epoch 4/15
5068/5068 [==============================] - 22s 4ms/step - loss: 0.0902 - acc: 0.9615
Epoch 5/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0898 - acc: 0.9639
Epoch 6/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0919 - acc: 0.9635
Epoch 7/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0849 - acc: 0.9653
Epoch 8/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0760 - acc: 0.9722
Epoch 9/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0850 - acc: 0.9667
Epoch 10/15
5068/5068 [==============================] - 21s 4ms/step - loss: 0.0805 - acc: 0.9678
Epoch 11/15
5068/50

In [151]:
predict=model.predict_classes(tfidf_test)
predict

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [152]:
score=accuracy_score(y_test,predict)
score

0.9250197316495659